name: MSYS2
on: [push]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: | 
            git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-cargo-c mingw-w64-ucrt-x86_64-rust mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-glib2 mingw-w64-ucrt-x86_64-gdk-pixbuf2 mingw-w64-ucrt-x86_64-gtk4 mingw-w64-ucrt-x86_64-pango mingw-w64-ucrt-x86_64-libxml2 mingw-w64-ucrt-x86_64-librsvg mingw-w64-ucrt-x86_64-libadwaita
      - name: CI-Build
        run: |
          rustc --print cfg
          # export RUSTFLAGS="-C target-feature=+crt-static"
          # cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          path: D:\a\hd2helper\hd2helper\target\release\hd2helper.exe
